export default {
	ADD_PLACE: "/add-place",
	CHAT: "/chat/",
	CHAT_FORM: "/chat/:chatId",
	EDIT_ACCOUNT: "/edit-account",
	EMAIL_VERIFY: "/email-verify",
	EMAIL_VERIFY_FORM: "/email-verify/:key",
	FIND_ADDRESS: "/find-address",
	HOME: "/",
	NUBER: "/nuber",
	PHONE_LOGIN: "/phone-login",
	PLACES: "/places",
	RIDE: "/ride/",
	RIDE_FORM: "/ride/:rideId",
	RIDE_HISTORY: "/ride-history",
	SETTING: "/setting",
	SIGN_UP: "/sign-up",
	SOCIAL_LOGIN: "/social-login",
	VERIFY_PHONE: "/verify-phone"
};
